version: "3.7"

services:
  postgres:
    container_name: bank-db
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
